spring.application.name=pdt-berenice-api1


server.port=8081

spring.cloud.openfeign.httpclient.hc5.enabled=true
app.security.aes-secret-key=12345678901234567890123456789012

spring.security.user.name=berenice
spring.security.user.password=admin123